version: '3.8'

services:
  sputnik:
    build: .
    container_name: sputnik-sfx
    restart: always
    network_mode: host
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sputnik_data:/data
      - sputnik_logs:/var/log
    sysctls:
      - net.core.rmem_max=67108864
      - net.core.wmem_max=67108864
      - net.core.rmem_default=16777216
      - net.core.wmem_default=16777216
      - net.core.netdev_max_backlog=100000

volumes:
  sputnik_data:
  sputnik_logs: